language: node_js
dist: trusty
sudo: required
node_js:
  - 8
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

stages:
  - build
  - test
  - report

jobs:
  include:
    - stage: build
      script:
        - npm install
        - npm run build
    - stage: test
      script: 
        - npm run test
      script:
        - npm run e2e
    - stage: report
      script: 'npm run coveralls'

addons:
  chrome: stable

  