language: node_js
dist: trusty
sudo: required
node_js:
  - 8
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

stages:
  - test

jobs:
  include:
    - stage: test
      script:
        - npm run test
      env: COMMAND=test:unit
      after_success: 'npm run coveralls'
    - stage: test
      script:
        - npm run e2e
      env: COMMAND=test:e2e

addons:
  chrome: stable
